import DB.Datepicker;
import db.DBConnection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.SimpleFormatter;
import javax.swing.ButtonGroup;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ADMIN_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN_WINDOW
     */
    public ADMIN_WINDOW()
    {
        initComponents();
        displayDriverlist();
        displayemployeelist();
        employee_id();
        carcompanycombofill();
        carlist();
    }
    
    public void employee_id()
    {
        try
        {
        DBConnection db = new DBConnection();
        db.stmt = db.con.createStatement();
        db.rs = db.stmt.executeQuery("select MAX(ID) from employee_list");
        db.rs.next();
        int id = db.rs.getInt(1);
        String eid = Integer.toString(id+1);
        jTextField23.setText(eid);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
                
    }
    
    public void carcompanycombofill()
    {
        try
        {
        DBConnection db = new DBConnection();
        String sql="select * from carcompany";
        db.pstmt= db.con.prepareStatement(sql);
        db.rs = db.pstmt.executeQuery();
        while(db.rs.next())
        {
            String name = db.rs.getString("CARNAME");
            jComboBox9.addItem(name);
            jComboBox6.addItem(name);
            jComboBox4.addItem(name);
        }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    public void displayDriverlist()
    {
        try
        {
        DBConnection db = new DBConnection();
        String sql = "select * from Drivers_list ";
        db.pstmt = db.con.prepareStatement(sql);
        db.rs = db.pstmt.executeQuery();
        jTable2.setModel(DbUtils.resultSetToTableModel(db.rs));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    public void carlist()
    {
        try
        {
            DBConnection db = new DBConnection();
            String sql = "select * from vehicle_list";
            db.pstmt = db.con.prepareStatement(sql);
            db.rs = db.pstmt.executeQuery();
            jTable4.setModel(DbUtils.resultSetToTableModel(db.rs));
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
               
    }
    public void displayemployeelist()
    {
        try
        {
            DBConnection db = new DBConnection();
            String sql = "select * from employee_list";
            db.pstmt = db.con.prepareStatement(sql);
            db.rs = db.pstmt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(db.rs));
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        ADD_EMPLOYEE = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jTextField11 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField8 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        ADDEMPLOYE_bg = new javax.swing.JLabel();
        MODIFY_EMPLOYEE = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jTextField15 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jTextField14 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        MODIFY_bg = new javax.swing.JLabel();
        EMPLOYEE_LIST = new javax.swing.JInternalFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        EMPLIST_bg = new javax.swing.JLabel();
        DRIVERS_LIST = new javax.swing.JInternalFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        DRIVELIST_bg = new javax.swing.JLabel();
        VIEW_CARS = new javax.swing.JInternalFrame();
        jPanel11 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jComboBox4 = new javax.swing.JComboBox<String>();
        jComboBox5 = new javax.swing.JComboBox<String>();
        jButton8 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton24 = new javax.swing.JButton();
        VIEWCAR_bg = new javax.swing.JLabel();
        ADDCOMPANY = new javax.swing.JInternalFrame();
        jPanel13 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<String>();
        jTextField17 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        ADD_VEHICLE = new javax.swing.JInternalFrame();
        jPanel14 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<String>();
        jComboBox9 = new javax.swing.JComboBox<String>();
        jComboBox10 = new javax.swing.JComboBox<String>();
        jComboBox11 = new javax.swing.JComboBox<String>();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jTextField20 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        ADDVEHICLE_bg = new javax.swing.JLabel();
        CHANGE_PASS = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jButton23 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        ADMIN_bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ADD_EMPLOYEE.setClosable(true);
        ADD_EMPLOYEE.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ADD_EMPLOYEE.setTitle("ADD EMPLOYEE");
        ADD_EMPLOYEE.setToolTipText("");
        ADD_EMPLOYEE.setVisible(false);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(153, 255, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LOGIN DETAILS");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("USERNAME :");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("NEW PASSWORD :");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CONFIRM PASSWORD :");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DATE OF JOINING :");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 200, -1));
        jPanel5.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 110, 30));

        jButton14.setText("Select");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 310, 90, -1));
        jPanel5.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 200, 30));

        jPasswordField2.setToolTipText("IT SHOULD BE SAME AS PREVIOUS FIELD");
        jPanel5.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 242, 200, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\project_img\\black.jpg")); // NOI18N
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 530));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 500, 550));

        jButton3.setText("SUBMIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, 120, 40));

        jButton4.setText("CANCEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 650, 120, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("NAME :");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("GENDER :");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ADDRESS :");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("QUALIFICATION :");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("D.O.B :");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("MOBILE :");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        jTextField9.setToolTipText("ONLY ALPHABETS ARE ALLOWED");
        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });
        jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 270, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 280, 130));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ", "NO EDUCATION", "HIGH SCHOOL", "INTERMEDIATE", "INTERMEDIATE+" }));
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 280, -1));

        jTextField11.setToolTipText("ONLY 10 DIGITS ARE ALLOWED");
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });
        jPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 280, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("MALE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("FEMALE");
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));
        jPanel4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 160, -1));

        jButton13.setText("Select");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 255));
        jLabel13.setText("ADD EMPLOYEE");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jTextField23.setEditable(false);
        jPanel4.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 270, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(240, 240, 240));
        jLabel55.setText("EMPLOYEE ID :");
        jPanel4.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jButton19.setText("RESET");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 650, 130, 40));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("OTHER");
        jPanel4.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        ADDEMPLOYE_bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\project_img\\black.jpg")); // NOI18N
        jPanel4.add(ADDEMPLOYE_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 710));

        javax.swing.GroupLayout ADD_EMPLOYEELayout = new javax.swing.GroupLayout(ADD_EMPLOYEE.getContentPane());
        ADD_EMPLOYEE.getContentPane().setLayout(ADD_EMPLOYEELayout);
        ADD_EMPLOYEELayout.setHorizontalGroup(
            ADD_EMPLOYEELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ADD_EMPLOYEELayout.setVerticalGroup(
            ADD_EMPLOYEELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(ADD_EMPLOYEE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 1070, 750));

        MODIFY_EMPLOYEE.setClosable(true);
        MODIFY_EMPLOYEE.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        MODIFY_EMPLOYEE.setTitle("MODIFY EMPLOYEE");
        MODIFY_EMPLOYEE.setVisible(false);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 255, 255));
        jLabel26.setText("MODIFY EMPLOYEE");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 255, 255));
        jLabel27.setText("ID :");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("NAME :");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(240, 240, 240));
        jLabel29.setText("GENDER :");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(240, 240, 240));
        jLabel30.setText("ADDRESS :");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(240, 240, 240));
        jLabel31.setText("D.O.B :");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("QUALIFICATION :");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("MOBILE :");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("DATE OF JOINING :");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));
        jPanel6.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 250, -1));

        jTextField13.setToolTipText("ONLY ALPHABETS ARE ALLOWED");
        jTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField13FocusLost(evt);
            }
        });
        jPanel6.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 270, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("MALE");
        jPanel6.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("FEMALE");
        jPanel6.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 280, 140));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ", "NO EDUCATION", "HIGH SCHOOL", "INTERMEDIATE", "INTERMEDIATE+" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 280, -1));

        jTextField15.setToolTipText("ONLY 10 DIGITS ARE ALLOWED");
        jTextField15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField15FocusLost(evt);
            }
        });
        jPanel6.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 250, -1));

        jButton5.setText("SUBMIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 170, 60));

        jButton6.setText("CANCEL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 160, 60));

        jButton7.setText("SEARCH");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, -1));
        jPanel6.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 280, 140));
        jPanel6.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 160, -1));

        jButton15.setText("Select");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));
        jPanel6.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 160, 30));

        jButton16.setText("Select");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, -1, 30));

        jButton20.setText("RESET");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 160, 60));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("OTHER");
        jPanel6.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        MODIFY_bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\project_img\\black.jpg")); // NOI18N
        jPanel6.add(MODIFY_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 710));

        javax.swing.GroupLayout MODIFY_EMPLOYEELayout = new javax.swing.GroupLayout(MODIFY_EMPLOYEE.getContentPane());
        MODIFY_EMPLOYEE.getContentPane().setLayout(MODIFY_EMPLOYEELayout);
        MODIFY_EMPLOYEELayout.setHorizontalGroup(
            MODIFY_EMPLOYEELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MODIFY_EMPLOYEELayout.setVerticalGroup(
            MODIFY_EMPLOYEELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(MODIFY_EMPLOYEE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 1060, 730));

        EMPLOYEE_LIST.setClosable(true);
        EMPLOYEE_LIST.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        EMPLOYEE_LIST.setTitle("EMPLOYEE LIST");
        EMPLOYEE_LIST.setVisible(false);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 255, 255));
        jLabel35.setText("EMPLOYEE LIST");
        jLabel35.setToolTipText("");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 340, 40));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpId", "Name", "Gender", "Address", "DOB", "Qualification", "Mobile", "Username", "Password", "DOJ"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 590));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 950, 590));

        EMPLIST_bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\project_img\\black.jpg")); // NOI18N
        jPanel7.add(EMPLIST_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 650));

        javax.swing.GroupLayout EMPLOYEE_LISTLayout = new javax.swing.GroupLayout(EMPLOYEE_LIST.getContentPane());
        EMPLOYEE_LIST.getContentPane().setLayout(EMPLOYEE_LISTLayout);
        EMPLOYEE_LISTLayout.setHorizontalGroup(
            EMPLOYEE_LISTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EMPLOYEE_LISTLayout.setVerticalGroup(
            EMPLOYEE_LISTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(EMPLOYEE_LIST, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 970, 690));

        DRIVERS_LIST.setClosable(true);
        DRIVERS_LIST.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        DRIVERS_LIST.setTitle("DRIVERS LIST");
        DRIVERS_LIST.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DRIVERS_LIST.setVisible(false);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 255, 255));
        jLabel36.setText("DRIVERS LIST");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 270, 40));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jPanel10.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 550));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 880, 560));

        DRIVELIST_bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\project_img\\black.jpg")); // NOI18N
        jPanel9.add(DRIVELIST_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 610));

        javax.swing.GroupLayout DRIVERS_LISTLayout = new javax.swing.GroupLayout(DRIVERS_LIST.getContentPane());
        DRIVERS_LIST.getContentPane().setLayout(DRIVERS_LISTLayout);
        DRIVERS_LISTLayout.setHorizontalGroup(
            DRIVERS_LISTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DRIVERS_LISTLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DRIVERS_LISTLayout.setVerticalGroup(
            DRIVERS_LISTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(DRIVERS_LIST, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 890, 650));

        VIEW_CARS.setClosable(true);
        VIEW_CARS.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        VIEW_CARS.setResizable(true);
        VIEW_CARS.setTitle("VIEW CARS");
        VIEW_CARS.setVisible(false);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 255, 255));
        jLabel37.setText("VIEW CARS");
        jPanel11.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("SELECT COMPANY :");
        jPanel11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 40));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(240, 240, 240));
        jLabel38.setText("SEATING CAPACITY :");
        jPanel11.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(240, 240, 240));
        jLabel39.setText("STATUS :");
        jPanel11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "AVAILABLE", "NOT AVAILABLE" }));
        jPanel11.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 260, 30));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT" }));
        jPanel11.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 260, 30));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel11.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 260, 30));

        jButton8.setText("VIEW CARS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 180, 40));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jPanel12.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 430));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 990, 430));

        jButton24.setText("SHOW ALL CARS");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 180, 40));

        VIEWCAR_bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\project_img\\black.jpg")); // NOI18N
        jPanel11.add(VIEWCAR_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 680));

        javax.swing.GroupLayout VIEW_CARSLayout = new javax.swing.GroupLayout(VIEW_CARS.getContentPane());
        VIEW_CARS.getContentPane().setLayout(VIEW_CARSLayout);
        VIEW_CARSLayout.setHorizontalGroup(
            VIEW_CARSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VIEW_CARSLayout.setVerticalGroup(
            VIEW_CARSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(VIEW_CARS, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 1010, 720));

        ADDCOMPANY.setClosable(true);
        ADDCOMPANY.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ADDCOMPANY.setTitle("ADD COMPANY");
        ADDCOMPANY.setVisible(false);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(240, 240, 240));
        jLabel41.setText("LIST OF COMAPNY :");
        jLabel41.setToolTipText("");
        jPanel13.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(240, 240, 240));
        jLabel42.setText("NEW COMAPNY NAME :");
        jPanel13.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 255, 255));
        jLabel43.setText("ADD COMPANY");
        jPanel13.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel13.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 260, 30));

        jTextField17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField17FocusLost(evt);
            }
        });
        jPanel13.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 260, 30));

        jButton9.setText("SUBMIT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 120, 40));

        jButton10.setText("CANCEL");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 130, 40));

        jButton21.setText("RESET");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 110, 40));

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\project_img\\black.jpg")); // NOI18N
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 360));

        javax.swing.GroupLayout ADDCOMPANYLayout = new javax.swing.GroupLayout(ADDCOMPANY.getContentPane());
        ADDCOMPANY.getContentPane().setLayout(ADDCOMPANYLayout);
        ADDCOMPANYLayout.setHorizontalGroup(
            ADDCOMPANYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ADDCOMPANYLayout.setVerticalGroup(
            ADDCOMPANYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(ADDCOMPANY, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 830, 400));

        ADD_VEHICLE.setClosable(true);
        ADD_VEHICLE.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ADD_VEHICLE.setTitle("ADD VEHICLE");
        ADD_VEHICLE.setVisible(false);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 255, 255));
        jLabel45.setText("ADD CAR");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(240, 240, 240));
        jLabel44.setText("CAR MODEL :");
        jPanel14.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(240, 240, 240));
        jLabel46.setText("CAR COMPANY :");
        jPanel14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(240, 240, 240));
        jLabel47.setText("CAR NUMBER :");
        jPanel14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(240, 240, 240));
        jLabel48.setText("MFG. YEAR :");
        jPanel14.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(240, 240, 240));
        jLabel49.setText("USE AS :");
        jPanel14.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(240, 240, 240));
        jLabel50.setText("SEATING CAPACITY :");
        jPanel14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("TYPE :");
        jPanel14.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(240, 240, 240));
        jLabel53.setText("ENGINE CAPACITY :");
        jPanel14.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(240, 240, 240));
        jLabel54.setText("RENT :");
        jPanel14.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Luxury", "Sports ", "Economic", "Sedan ", "CarryCar", " " }));
        jPanel14.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 230, 30));

        jPanel14.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 240, 30));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "CITY RIDE", "STATE RIDE", "COUNTRY RIDE", " " }));
        jPanel14.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 240, 30));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel14.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 240, 30));
        jPanel14.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 240, 40));
        jPanel14.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 240, 40));
        jPanel14.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 230, 30));

        jTextField22.setToolTipText("ONLY NUMERIC ARE ALLOWED");
        jTextField22.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField22FocusLost(evt);
            }
        });
        jPanel14.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 230, 30));

        jButton11.setText("SUBMIT");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 150, 50));

        jButton12.setText("CANCEL");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 590, 130, 50));
        jPanel14.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 150, 30));

        jButton18.setText("SELECT");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 80, 30));

        jButton22.setText("RESET");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, 150, 50));

        ADDVEHICLE_bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\project_img\\black.jpg")); // NOI18N
        jPanel14.add(ADDVEHICLE_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 740));

        javax.swing.GroupLayout ADD_VEHICLELayout = new javax.swing.GroupLayout(ADD_VEHICLE.getContentPane());
        ADD_VEHICLE.getContentPane().setLayout(ADD_VEHICLELayout);
        ADD_VEHICLELayout.setHorizontalGroup(
            ADD_VEHICLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ADD_VEHICLELayout.setVerticalGroup(
            ADD_VEHICLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(ADD_VEHICLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 1110, 780));

        CHANGE_PASS.setClosable(true);
        CHANGE_PASS.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        CHANGE_PASS.setResizable(true);
        CHANGE_PASS.setTitle("Change Password");
        CHANGE_PASS.setVisible(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("CHANGE PASSWORD");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter User Name :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Old Password :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter New Password :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirm New Password :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 110, 40));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 100, 40));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 240, 30));
        jPanel3.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 240, 30));
        jPanel3.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 240, 30));

        jPasswordField5.setToolTipText("NEW PASSSWORD AND CONFIRM PASSWRD SHOULD BE SAME");
        jPanel3.add(jPasswordField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 240, 30));

        jButton23.setText("RESET");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 100, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\project_img\\black.jpg")); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        javax.swing.GroupLayout CHANGE_PASSLayout = new javax.swing.GroupLayout(CHANGE_PASS.getContentPane());
        CHANGE_PASS.getContentPane().setLayout(CHANGE_PASSLayout);
        CHANGE_PASSLayout.setHorizontalGroup(
            CHANGE_PASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CHANGE_PASSLayout.setVerticalGroup(
            CHANGE_PASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(CHANGE_PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 860, 590));

        jButton17.setText("LOG OUT");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 20, -1, -1));

        ADMIN_bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\new image\\admi.jpg")); // NOI18N
        jDesktopPane1.add(ADMIN_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 1030));

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 1030));

        jMenu1.setText("Employee");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Add Employee");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Modify Employee");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View Records");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Employee List");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Driver List");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("View Car");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Vehicles");

        jMenuItem6.setText("Add Company");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Add Vehicle");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Others");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Change Password");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     if(jTextField9.getText().equals("")||jTextArea1.getText().equals("")||jTextField8.getText().equals("")||jComboBox1.getSelectedItem().toString().equals("")||jTextField11.getText().equals("")||jTextField5.getText().equals("")||jPasswordField1.getText().equals("")||jPasswordField2.getText().equals("")||jTextField11.getText().equals(""))
          {
             JOptionPane.showMessageDialog(this,"PLEASE FILL ALL THE BLANKS");
          }
     else
     {
      try
      {
       DBConnection db =  new DBConnection();
       String name = jTextField9.getText();
       int id = Integer.parseInt(jTextField23.getText());
       String address = jTextArea1.getText();
       String dob = jTextField8.getText();
       String quali = jComboBox1.getSelectedItem().toString();
       String mob =  jTextField11.getText();
       String doj = jTextField10.getText();
       String username = jTextField5.getText();
       int npass = Integer.parseInt(jPasswordField1.getText());
       int cpass = Integer.parseInt(jPasswordField2.getText());
       
       //CODE FOR RADIO BUTTON ON GENDER OPTION.
       
       String gender = "";

        if(jRadioButton1.isSelected())
        {
            gender = "MALE";
        }
        if(jRadioButton2.isSelected())
        {
            gender = "FEMALE";
        }
        if(jRadioButton5.isSelected())
        {
            gender = "OTHER";
        }
        
        //CODE TO MATCH NEW PASSWORD AND CONFIRM PASSWORD.
        
         
          else
          
           if(cpass==npass)
            {
            db.stmt = db.con.createStatement();
            String query = "insert into employee_list values('"+id+"','"+name+"','"+gender+"','"+address+"','"+dob+"','"+quali+"','"+mob+"','"+username+"','"+cpass+"','"+doj+"')";
            int i = db.stmt.executeUpdate(query);
            if(i>0)
            {
                JOptionPane.showMessageDialog(this,"Employee Successfully Added !");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Something Went Wrong !");
            }  
         
           
           
           
            }
            else
            {
            JOptionPane.showMessageDialog(this, "Password does not Match !");
            }
           
          }
      catch(Exception e)
      {
          e.printStackTrace();
      }
        
        
        
                
       
      }
      
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ADD_EMPLOYEE.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       MODIFY_EMPLOYEE.setVisible(true);
       MODIFY_EMPLOYEE.repaint();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       
        displayemployeelist();
        EMPLOYEE_LIST.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        displayDriverlist();
       DRIVERS_LIST.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        carlist();    
        VIEW_CARS.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ADDCOMPANY.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
      ADD_VEHICLE.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       CHANGE_PASS.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ADD_EMPLOYEE.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        MODIFY_EMPLOYEE.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jTextField14.getText().equals("")||jTextField15.getText().equals("")||jTextField16.getText().equals("")||jTextField12.getText().equals("")||jTextField13.getText().equals("")||jComboBox2.getSelectedItem().equals(""))
        {
            JOptionPane.showMessageDialog(this,"PLEASE FILL ALL THE FIELDS");
        }
        else
        {
       
       try
       {
       DBConnection db = new DBConnection();
       String name = jTextField13.getText().toString();
       int id = Integer.parseInt(jTextField12.getText());
       String address = jTextArea2.getText().toString();
       String dob = jTextField14.getText();
       String quali = jComboBox2.getSelectedItem().toString();
       String mob =  jTextField15.getText();
       String doj = jTextField16.getText();
     
       String gender="";
      
       if(jRadioButton3.isSelected())
       {
           gender ="MALE";
       }
       if(jRadioButton4.isSelected())
       {
           gender ="FEMALE";
       }
       if(jRadioButton4.isSelected())
        {
            gender = "OTHER";
        }
       String sql ="update employee_list set NAME ='"+name+"', GENDER = '"+gender+"', ADDRESS = '"+address+"', DOB='"+dob+"',QUALIFICATION ='"+quali+"',MOBILE ='"+mob+"',DOJ='"+doj+"' where ID='"+id+"'";
       db.stmt = db.con.createStatement();
       int i = db.stmt.executeUpdate(sql);
      
       if(i>0)
       {
           JOptionPane.showMessageDialog(this,"Employee Details Successfully Updated ! ");
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Something Went Wrong !");
       }
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
       }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       try
       {
        DBConnection db = new DBConnection();
        int id = Integer.parseInt(jTextField12.getText());
        String sql = "select * from employee_list where id='"+id+"'";
        db.stmt=db.con.createStatement();
        db.rs = db.stmt.executeQuery(sql);
        if(db.rs.next())
        {
            jTextField13.setText(db.rs.getString(2));
            String gen = db.rs.getString(3);
            if("MALE".equals(gen))
            {
                jRadioButton3.setSelected(true);
            }
            else
            {
                jRadioButton4.setSelected(true);
            }
            jTextArea2.setText(db.rs.getString(4));
            String datevalue = db.rs.getString(5);
            jComboBox2.setSelectedItem(db.rs.getString(6));
            jTextField15.setText(db.rs.getString(7));
            String datevalue1 = db.rs.getString(10);
            jTextField14.setText(db.rs.getString(5));
            jTextField16.setText(db.rs.getString(10));
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Data Not Found !");
        }
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try
        {
        DBConnection db = new DBConnection();
        String comp = jComboBox4.getSelectedItem().toString();
        int capacity = Integer.parseInt(jComboBox5.getSelectedItem().toString());
        String status = jComboBox3.getSelectedItem().toString();
        String sql = "select * from vehicle_list where COMPANY='"+comp+"' AND SEATING_CAPACITY='"+capacity+"' AND STATUS='"+status+"'";
        db.pstmt = db.con.prepareStatement(sql);
        db.rs = db.pstmt.executeQuery();
        jTable4.setModel(DbUtils.resultSetToTableModel(db.rs));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        ADDCOMPANY.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       if(jTextField17.getText().equals(""))
       {
           JOptionPane.showMessageDialog(this,"Please Fill All The fields");
       }
       else
       {
       try
       {
       DBConnection db = new DBConnection();
       String comp = jTextField17.getText().toString();
       String sql = "insert into carcompany values ('"+ comp +"')";
       db.stmt = db.con.createStatement();
       int i = db.stmt.executeUpdate(sql);
       if(i>0)
       {
           JOptionPane.showMessageDialog(this,"Company Added Successfully !");
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Failed To Add Company!");
       }
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
       }
            
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
      ADD_VEHICLE.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(jTextField18.getText().equals("")||jComboBox9.getSelectedItem().equals("")||jTextField19.getText().equals("")||jTextField20.getText().equals("")||jComboBox11.getSelectedItem().equals("")||jComboBox10.getSelectedItem().equals("")||jComboBox7.getSelectedItem().equals("")||jTextField21.getText().equals("")||jTextField22.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Fill All The Fields");
        }
        else
        {
        try
        {
        DBConnection db = new DBConnection();
        String model = jTextField18.getText();
        String company = jComboBox9.getSelectedItem().toString();
        String Number = jTextField19.getText();
        String mfg = jTextField20.getText();
        String useas = jComboBox10.getSelectedItem().toString();
        String capacity = jComboBox11.getSelectedItem().toString();
        String type = jComboBox7.getSelectedItem().toString();
        String engine = jTextField21.getText();
        String rent = jTextField22.getText();
        String status = "AVAILABLE";
        String sql = "insert into vehicle_list values('"+company+"','"+model+"','"+Number+"','"+mfg+"','"+ useas+"','"+capacity+"','"+type+"','"+engine+"','"+rent+"','"+status+"')";
        db.stmt = db.con.createStatement();
        int i = db.stmt.executeUpdate(sql);
        if(i>0)
        {
            JOptionPane.showMessageDialog(this,"New Car Is Added Successfully !");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Car Registration Failed !");
        }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        }
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       CHANGE_PASS.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField1.getText().equals("")||jPasswordField3.getText().equals("")||jPasswordField4.getText().equals(evt)||jPasswordField5.getText().equals(""))
        {
         JOptionPane.showMessageDialog(this,"Please Fill All The Fields");
        }
        else
        {
        try
        {
        DBConnection db = new DBConnection();
        String username = jTextField1.getText();
        int opass = Integer.parseInt(jPasswordField3.getText());
        int npass = Integer.parseInt(jPasswordField4.getText());
        int cpass = Integer.parseInt(jPasswordField5.getText());
        
        String sql = "Select COUNT(*) from loginadmin where username= '"+username+"' and password ='"+opass+"'";
        db.stmt = db.con.createStatement();
        db.rs = db.stmt.executeQuery(sql);
        if(db.rs.next())
        {
            if(cpass == npass)
            {
                String sql1 = "update loginadmin set password = '"+cpass+"' where username = '"+username+"'";
                int j = db.stmt.executeUpdate(sql1);
                if(j>0)
                {
                    JOptionPane.showMessageDialog(this,"Password Changed Successfully !");
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Unable To Change Password !");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Password Confirmation Does Not Match");
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this,"You Entered Wrong Username and Password!");
        }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        }        
           
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

 Datepicker d = new Datepicker(new ADMIN_WINDOW());
        jTextField8.setText(d.setPickedDate());

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

Datepicker d = new Datepicker(new ADMIN_WINDOW());
        jTextField10.setText(d.setPickedDate());

  

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        Datepicker d = new Datepicker(new ADMIN_WINDOW());
        jTextField16.setText(d.setPickedDate());

  

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        Datepicker d = new Datepicker(new ADMIN_WINDOW());
        jTextField16.setText(d.setPickedDate());
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        this.setVisible(false);
        LOGIN_WINDOW lg = new LOGIN_WINDOW();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        Datepicker dp = new Datepicker(new ADMIN_WINDOW());
        jTextField20.setText(dp.setPickedDate());
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
     String str = jTextField9.getText();
     char ch;
     int asc; 
     for(int i=0;i<=str.length();i++)
     {
         ch = str.charAt(i);
         asc=ch;
         if(asc>=48&&asc<=57)
         {
         
              
                    JOptionPane.showMessageDialog(this,"Only Alphabets are allowed ");
                    jTextField9.setText("");
                    break;
                
         }
     }
                
    
     
     
    }//GEN-LAST:event_jTextField9FocusLost

    private void jTextField13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusLost
        
     String str = jTextField13.getText();
     char ch;
     int asc;
     for(int i=0;i<=str.length();i++)
     {
         ch = str.charAt(i);
         asc=ch;
         if(asc>=48&&asc<=57)
         {
            
            JOptionPane.showMessageDialog(this,"Only Alphabets are allowed ");
            jTextField13.setText("");
            break;
             
         }
     }
     
    }//GEN-LAST:event_jTextField13FocusLost

    private void jTextField17FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField17FocusLost
     String str = jTextField17.getText();
     char ch;
     int asc;
     for(int i=0;i<=str.length();i++)
     {
         ch = str.charAt(i);
         asc=ch;
         if(asc>=48&&asc<=57)
         {
          
         JOptionPane.showMessageDialog(this,"Only Alphabets are allowed ");
         jTextField17.setText("");
         break;
             
         }
     }
    
    }//GEN-LAST:event_jTextField17FocusLost

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        String mobi = jTextField11.getText();
        char ch;
        int asc;
       
        for(int i=0;i<=mobi.length();i++)
        {
            ch = mobi.charAt(i);
            asc=ch;
            
            if(!(asc>=48&&asc<=57)||mobi.length()!=10)
            {
            JOptionPane.showMessageDialog(this,"Mobile Must Be Numeric and Having 10 Digits");
            jTextField11.setText("");
            break;
            }
                    
        }
        
                
    }//GEN-LAST:event_jTextField11FocusLost

    private void jTextField15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField15FocusLost
        String mobi = jTextField15.getText();
        char ch;
        int asc;
        for(int i=0;i<=mobi.length();i++)
        {   
            ch = mobi.charAt(i);
            asc=ch;
            if(!(asc>=48&&asc<=57)||mobi.length()!=10)
            {
                 JOptionPane.showMessageDialog(this,"Mobile Must Be Numeric and Having 10 Digits");
                 jTextField15.setText("");
                 break;
            }
                    
        }
       
        
        
        
    }//GEN-LAST:event_jTextField15FocusLost

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
       jTextField23.setText("");
       jTextField9.setText("");
       jTextField8.setText("");
       jTextField11.setText("");
       jTextField5.setText("");
       jTextField10.setText("");
       jPasswordField1.setText("");
       jPasswordField2.setText("");
       jComboBox1.setSelectedIndex(0);
       jTextArea1.setText("");
       
       
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextArea2.setText("");
        jComboBox2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
      jTextField17.setText("");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        jTextField18.setText("");
        jTextField19.setText("");
        jTextField20.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        jComboBox10.setSelectedIndex(0);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        jTextField1.setText("");
        jPasswordField3.setText("");
        jPasswordField4.setText("");
        jPasswordField5.setText("");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        try
        {
        DBConnection db = new DBConnection();
        String sql="select * from vehicle_list ";
        db.pstmt = db.con.prepareStatement(sql);
        db.rs = db.pstmt.executeQuery();
        jTable4.setModel(DbUtils.resultSetToTableModel(db.rs));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jTextField22FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField22FocusLost
       String mobi = jTextField15.getText();
        char ch;
        int asc;
        for(int i=0;i<=mobi.length();i++)
        {   
            ch = mobi.charAt(i);
            asc=ch;
            if(!(asc>=48&&asc<=57))
            {
                 JOptionPane.showMessageDialog(this,"Rent Must Be Numeric ");
                 jTextField15.setText("");
                 break;
            }
                    
        }
    }//GEN-LAST:event_jTextField22FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN_WINDOW().setVisible(true);
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame ADDCOMPANY;
    private javax.swing.JLabel ADDEMPLOYE_bg;
    private javax.swing.JLabel ADDVEHICLE_bg;
    private javax.swing.JInternalFrame ADD_EMPLOYEE;
    private javax.swing.JInternalFrame ADD_VEHICLE;
    private javax.swing.JLabel ADMIN_bg;
    private javax.swing.JInternalFrame CHANGE_PASS;
    private javax.swing.JLabel DRIVELIST_bg;
    private javax.swing.JInternalFrame DRIVERS_LIST;
    private javax.swing.JLabel EMPLIST_bg;
    private javax.swing.JInternalFrame EMPLOYEE_LIST;
    private javax.swing.JInternalFrame MODIFY_EMPLOYEE;
    private javax.swing.JLabel MODIFY_bg;
    private javax.swing.JLabel VIEWCAR_bg;
    private javax.swing.JInternalFrame VIEW_CARS;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
